/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UwuImport } from './routes/uwu'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const UwuRoute = UwuImport.update({
  path: '/uwu',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/uwu': {
      id: '/uwu'
      path: '/uwu'
      fullPath: '/uwu'
      preLoaderRoute: typeof UwuImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/uwu': typeof UwuRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/uwu': typeof UwuRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/uwu': typeof UwuRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/uwu'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/uwu'
  id: '__root__' | '/' | '/uwu'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UwuRoute: typeof UwuRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UwuRoute: UwuRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/uwu"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/uwu": {
      "filePath": "uwu.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
